## [作業重點]
使用 Sklearn 中的 Lasso, Ridge 模型，來訓練各種資料集，務必了解送進去模型訓練的**資料型態**為何，也請了解模型中各項參數的意義。

機器學習的模型非常多種，但要訓練的資料多半有固定的格式，確保你了解訓練資料的格式為何，這樣在應用新模型時，就能夠最快的上手開始訓練！

## 練習時間
試著使用 sklearn datasets 的其他資料集 (boston, ...)，來訓練自己的線性迴歸模型，並加上適當的正則化來觀察訓練情形。

In [10]:

import numpy as np
from sklearn.linear_model import LinearRegression,Lasso
from sklearn.model_selection import train_test_split
from sklearn import datasets

In [2]:

boston=datasets.load_boston()
trainx,testx,trainy,testy=train_test_split(boston.data,boston.target,test_size=0.1)

In [3]:
reg=LinearRegression()
reg.fit(trainx,trainy)
py_pred = reg.predict(testx)

In [4]:

py_pred

array([16.47275009, 24.15138765, 20.49467455, 12.61226824, 24.79712936,
       22.40846647, 18.07441967, 21.3568655 , 27.81387888, 32.33034479,
       23.13159697, 28.48281787, 26.56375284, 30.7176811 , 27.28949488,
       14.21157572, 31.10674008, 34.89946163, 25.39287996, 28.33759509,
       18.13345028, 25.10428902, 14.017226  , 19.80095374, 30.93817388,
       19.85683429, 21.49627296, 30.88822536, 19.66707903, 29.10884626,
        4.15714669, 23.38547006, 25.04972729, 30.32021401, 33.44214307,
       17.17483359, 17.59408145, 22.42343101, 27.71736059, 34.41943858,
       20.33380302, 25.13702111, 17.02857954, 22.2771617 , 16.76613461,
       24.28025328, 29.33642718, 24.17646133, 36.71998146, 44.08299637,
       31.71305869])

In [5]:
reg.coef_

array([-1.02430863e-01,  4.28839646e-02,  1.37555787e-02,  2.18461372e+00,
       -1.71522798e+01,  3.74571223e+00, -8.28866230e-03, -1.47204845e+00,
        2.79944108e-01, -1.21685989e-02, -9.91742503e-01,  8.39237737e-03,
       -4.87791403e-01])

In [6]:
from sklearn.metrics import mean_squared_error, r2_score


In [7]:
mean_squared_error(testy, py_pred)


35.1507663465136

In [13]:
lasso = Lasso(alpha=10.0)
lasso.fit(trainx,trainy)
y_pred = lasso.predict(testx)
lasso.coef_


array([-0.        ,  0.02358346, -0.        ,  0.        ,  0.        ,
        0.        ,  0.        , -0.        ,  0.        , -0.01067344,
       -0.        ,  0.00625427, -0.53635166])

In [14]:

mean_squared_error(testy, y_pred)

62.06462402636202

In [15]:
lasso = Lasso(alpha=1.0)
lasso.fit(trainx,trainy)
y_pred = lasso.predict(testx)
lasso.coef_
mean_squared_error(testy, y_pred)

43.72057321308108